-- MySQL Script generated by MySQL Workbench
-- Sun Oct  6 13:28:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`account` (
  `UserID` INT NOT NULL,
  `UserName` VARCHAR(50) NULL DEFAULT NULL,
  `Password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`course` (
  `CourseID` INT NOT NULL,
  `CourseName` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CourseID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`exam` (
  `CourseID` INT NULL DEFAULT NULL,
  `QuestionID` INT NOT NULL,
  `ExamID` INT NULL DEFAULT NULL,
  `ExamNam` VARCHAR(100) NULL DEFAULT NULL,
  `Deadline` DATE NULL DEFAULT NULL,
  `Duration` INT NULL DEFAULT NULL,
  PRIMARY KEY (`QuestionID`),
  INDEX `CourseID` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `exam_ibfk_1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `project`.`course` (`CourseID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`question` (
  `exam_id` VARCHAR(50) NULL DEFAULT NULL,
  `question_id` VARCHAR(50) NULL DEFAULT NULL,
  `question_type` VARCHAR(20) NULL DEFAULT NULL,
  `grade` DECIMAL(3,2) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`question_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`question_answer` (
  `question_id` VARCHAR(50) NULL DEFAULT NULL,
  `answer_id` VARCHAR(50) NULL DEFAULT NULL,
  `true_answer` ENUM('A', 'B', 'C', 'D', 'True', 'False') NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`result` (
  `course_id` VARCHAR(50) NULL DEFAULT NULL,
  `exam_id` VARCHAR(50) NULL DEFAULT NULL,
  `exam_name` TINYTEXT NULL DEFAULT NULL,
  `student_id` VARCHAR(50) NULL DEFAULT NULL,
  `student_name` TINYTEXT NULL DEFAULT NULL,
  `grade` DECIMAL(3,2) NULL DEFAULT NULL,
  `feadback` LONGTEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`student` (
  `StudentID` INT NOT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `Age` INT NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`student_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`student_answer` (
  `question_id` VARCHAR(50) NULL DEFAULT NULL,
  `choose_option` CHAR(1) NULL DEFAULT NULL,
  `student_id` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`teacher` (
  `TecherID` INT NOT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`TecherID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
